[supervisord]
nodaemon=true

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
priority=5

[program:queue-worker]
command=php /var/www/html/bin/worker.php
autostart=true
autorestart=true
priority=10
startretries=10
